Environment=Local / CI
Project=QA Automation Test Suite
Author=Vasyl Kachala
Framework=JUnit 5 + REST Assured + Playwright
Reporting=Allure
RestfulBooker=https://restful-booker.herokuapp.com
GraphQL=Hygraph Video schema
UI=https://demoqa.com
